-- ============================================
-- 小元书屋 后端数据库表结构
-- 在 Supabase → SQL Editor 中全部粘贴 → Run
-- ============================================

-- 1. 用户表
create table if not exists users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  is_admin boolean default false,
  created_at timestamp default now()
);
alter table users enable row level security;
create policy "users_all" on users for all using (true);

-- 2. 订单表
create table if not exists orders (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  username text not null,
  book_id text not null,
  book_title text not null,
  price numeric(10,2) default 0.99,
  status text default 'pending_verification',
  created_at timestamp default now(),
  verified_at timestamp,
  verified_by text,
  reject_reason text
);
alter table orders enable row level security;
create policy "orders_all" on orders for all using (true);

-- 3. 购买记录表
create table if not exists purchases (
  id bigint generated by default as identity primary key,
  username text not null,
  book_id text not null,
  order_id text not null,
  price numeric(10,2) default 0.99,
  book_title text,
  status text default 'paid',
  purchased_at timestamp default now()
);
alter table purchases enable row level security;
create policy "purchases_all" on purchases for all using (true);

-- 4. 阅读进度表
create table if not exists progress (
  id bigint generated by default as identity primary key,
  username text not null,
  book_id text not null,
  chapter_index int default 0,
  scroll_top int default 0,
  updated_at timestamp default now()
);
alter table progress enable row level security;
create policy "progress_all" on progress for all using (true);

-- 5. 创建索引
create index if not exists idx_orders_username on orders(username);
create index if not exists idx_orders_status on orders(status);
create index if not exists idx_purchases_username on purchases(username);
create index if not exists idx_progress_username on progress(username);
